repos:
- hooks:
  - id: black
    language_version: python3
  repo: https://github.com/ambv/black
  rev: 22.1.0
- hooks:
  - id: flake8
  repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.21.2
